return added
js-tasks-ru/jsbasic-20220708_sukhanovaas01 pull request #1
Opened 2022-07-11 18:39 UTC by AnastasiaSukhanova

2022-07-11 18:39 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @koalex должен запустить тесты.

2022-07-13 03:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-13 03:58 UTC, koalex requested changes
Зачем удалили задачу? нужно вернуть решение **0-1**

2022-07-15 16:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-07-15 16:52 UTC, koalex approved these changes

2022-07-15 16:52 UTC, koalex commented on 1-module/4-task/index.js
> +    if ( str.includes('1XBET') || str.includes('XXX')) {
`return str.includes('1XBET') || str.includes('XXX');`

2022-07-15 16:53 UTC, merged